import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Outfit } from "next/font/google";
import Script from "next/script";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/footer/Footer";
import LenisWrapper from "@/components/layout/lenisWrapper";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Indoshyama Fertilizers Pvt. Ltd.",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased scrollbar-none`}>
        {/* Wrap everything with LenisWrapper for smooth scrolling */}
        <LenisWrapper>
          <NavBar />
          <main>{children}</main>
          <Footer />
        </LenisWrapper>

        {/* Preline script */}
        <Script
          src="https://unpkg.com/preline/dist/preline.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
